// @ts-check
// TDAD Playwright Configuration - Generated by TDAD
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './workflows',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: 'html',
  timeout: 20000,
  globalSetup: './globalSetup.js',

  use: {
    trace: 'on-first-retry',
    baseURL: 'http://localhost:3000',
  },

  projects: [
    {
      name: 'ui',
      use: { baseURL: 'http://localhost:3000' },
      grep: /\[(UI|API)-\d+\]/,  // Match [UI-xxx] and [API-xxx] tests
    }
  ],
});
