// @ts-check
// TDAD Playwright Configuration - Generated by TDAD
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './workflows',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: 'html',
  timeout: 20000,

  use: {
    trace: 'on-first-retry',
    baseURL: 'http://localhost:3000',
  },

  webServer: {
    command: 'cmd /c D:\\source\\repos\\zekeriyademir\\IsItJustMe\\start-server.bat',
    url: 'http://localhost:3000',
    reuseExistingServer: true,
    timeout: 120000,
    stdout: 'pipe',
    stderr: 'pipe',
  },

  projects: [
    {
      name: 'ui',
      use: { baseURL: 'http://localhost:3000' },
      grep: /\[(UI|API)-\d+\]/,  // Match [UI-xxx] and [API-xxx] tests
    }
  ],
});
